name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        package-manager: [npm, yarn]
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - name: Install dependencies with ${{ matrix.package-manager }}
      run: |
        if [ "${{ matrix.package-manager }}" = "npm" ]; then
          npm install
        else
          yarn
        fi
    
    - name: Run linting
      run: |
        if [ "${{ matrix.package-manager }}" = "npm" ]; then
          npm run lint
        else
          yarn lint
        fi
    
    - name: Run tests
      run: |
        if [ "${{ matrix.package-manager }}" = "npm" ]; then
          npm test
        else
          yarn test
        fi
    
    - name: Build project
      run: |
        if [ "${{ matrix.package-manager }}" = "npm" ]; then
          npm run build
        else
          yarn build
        fi
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts-${{ matrix.package-manager }}
        path: dist/
        retention-days: 5 